---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: Provision of instance
      ec2:
        
         aws_access_key: ACCESS_KEY
         aws_secret_key: SECRET_KEY
        
         instance_type: m1.small
         image: ami-26d87c46
         wait: true
         region: us-west-2
         exact_count: 1
         count_tag:
            Name: sohan
         instance_tags:
            Name: sohan
      register: ec2
